FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates tzdata curl tar \
    && mkdir -p /app/bin \
    && curl -sL https://github.com/rhasspy/piper/releases/download/2023.11.14-2/piper_linux_x86_64.tar.gz | tar -xzC /app/bin \
    && apt-get purge -y curl && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY bin/dialer-go ./dialer-go
COPY models/ ./models/
COPY mode/ ./mode/

EXPOSE 8080
EXPOSE 8081

CMD ["./dialer-go"]
