[modules]
autoload=yes

; Preload PJSIP core
preload => res_pjsip.so
preload => res_pjsip_session.so

; Módulos essenciais de telefonia, mídia e codecs
load => res_rtp_asterisk.so
load => res_sorcery_config.so
load => res_sorcery_memory.so
load => res_pjproject.so
load => chan_pjsip.so
load => app_playback.so
load => app_agi.so
load => app_verbose.so
load => app_dial.so
load => app_waitforring.so
load => codec_alaw.so
load => codec_ulaw.so
load => codec_gsm.so
load => format_wav.so
load => format_wav_gsm.so
load => format_pcm.so

; Módulos desnecessários desativados
noload => chan_sip.so
noload => chan_iax2.so
noload => chan_skinny.so
noload => chan_unistim.so
